modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/GrowthcraftCE/Growthcraft-1.15/issues"

[[mods]]
    modId="growthcraft"
    version="5.0.0"
    displayName="Growthcraft"
    updateJSONURL="https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-versions.json"
    displayURL="https://github.com/GrowthcraftCE/Growthcraft-1.15/wiki"
    logoFile="growthcraft_core_logo.png"
    credits="Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
    authors="Alatyami, CoffeeThief"
    description='''
    Growtchraft is a realistic and immersive Forge mod that adds various new elements to the game of Minecraft.
    '''

    [[dependencies.growthcraft]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.growthcraft]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.growthcraft]]
        modId="patchouli"
        mandatory=false
        versionRange="[1.15.2-1.2-32,)"
        side="BOTH"

[[mods]]
    modId="growthcraft_apples"
    version="5.0.0"
    displayName="Growtchraft Apples"
    logoFile="growthcraft_apples_logo.png"
    description='''
    As a child mod to Growthcraft, Growthcraft Apples adds Apple Cider, Apple Tree and various apple woord based blocks and items.
    '''

    [[dependencies.growthcraft_apples]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_bamboo"
    version="5.0.0"
    displayName="Growtchraft Bamboo"
    logoFile="growthcraft_bamboo_logo.png"
    description='''
    As a child mod to Growthcraft, Growthcraft Apples adds Apple Cider, Apple Tree and various apple woord based blocks and items.
    '''

    [[dependencies.growthcraft_bamboo]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_bees"
    version="5.0.0"
    displayName="Growtchraft Bees"
    logoFile="growthcraft_bees_logo.png"
    description='''
    As a child mod to Growthcraft, Growthcraft Apples adds Apple Cider, Apple Tree and various apple woord based blocks and items.
    '''

    [[dependencies.growthcraft_bees]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_cellar"
    version="5.0.0"
    displayName="Growtchraft Cellar"
    logoFile="growthcraft_cellar_logo.png"
description = '''
    As a child mod to Growthcraft...
    '''

[[dependencies.growthcraft_cellar]]
modId = "growthcraft"
mandatory = true
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_deco"
version = "5.0.0"
displayName = "Growtchraft Decorations"
logoFile = "growthcraft_core_logo.png"
description = '''
    As a child mod to Growthcraft that provides decrotive blocks to the game.
    '''

[[dependencies.growthcraft_cellar]]
modId = "growthcraft"
mandatory = true
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_grapes"
version = "5.0.0"
displayName = "Growtchraft Grapes"
logoFile = "growthcraft_grapes_logo.png"
description = '''
    As a child mod to Growthcraft...
    '''

    [[dependencies.growthcraft_grapes]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_hops"
    version="5.0.0"
    displayName="Growtchraft Hops"
    logoFile="growthcraft_hops_logo.png"
    description='''
    As a child mod to Growthcraft...
    '''

    [[dependencies.growthcraft_hops]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_milk"
    version="5.0.0"
    displayName="Growtchraft Milk"
    logoFile="growthcraft_Milk_logo.png"
    description='''
    As a child mod to Growthcraft...
    '''

    [[dependencies.growthcraft_milk]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_rice"
    version="5.0.0"
    displayName="Growtchraft Rice"
    logoFile="growthcraft_rice_logo.png"
    description='''
    As a child mod to Growthcraft...
    '''

    [[dependencies.growthcraft_rice]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"

[[mods]]
    modId="growthcraft_trapper"
    version="5.0.0"
    displayName="Growtchraft Trapper"
    logoFile="growthcraft_trapper_logo.png"
    description='''
    As a child mod to Growthcraft...
    '''

    [[dependencies.growthcraft_trapper]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"
