modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/GrowthcraftCE/Growthcraft-1.15/issues" #optional

[[mods]]
    modId="growthcraft"
    version="5.0.0"
    displayName="Growthcraft"
    updateJSONURL="https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-versions.json"
    displayURL="https://github.com/GrowthcraftCE/Growthcraft-1.15/wiki"
    logoFile="growthcraft_core_logo.png"
    credits="Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
    authors="Alatyami, CoffeeThief"
    description='''
    Growtchraft is a realistic and immersive Forge mod that adds various new elements to the game of Minecraft.
    '''

    [[dependencies.growthcraft]] #optional
        modId="forge" #mandatory
        mandatory=true #mandatory
        versionRange="[31,)" #mandatory
        ordering="NONE"
        side="BOTH"
    [[dependencies.growthcraft]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"

[[mods]]
    modId="growthcraft_apples"
    version="5.0.0"
    displayName="Growtchraft Apples"
    logoFile="growthcraft_apples_logo.png"
    description='''
    As a child mod to Growthcraft, Growthcraft Apples adds Apple Cider, Apple Tree and various apple woord based blocks and items.
    '''

    [[dependencies.growthcraft_trapper]]
        modId="growthcraft"
        mandatory=true
        versionRange="[5,)"
        ordering="AFTER"
        side="BOTH"